version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "26656-26657:26656-26657"
    volumes:
      - config-volume:/chain_main/config
      - db-volume:/chain_main/data
volumes:
  config-volume:
    external: true
  db-volume:
    external: true

