---
- name: Configure Docker
  hosts: all
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
      tags: docker

    - name: Start and enable Docker
      systemd:
        name: docker
        enabled: yes
        state: started
      tags: docker